<?php
/**
 * Created by PhpStorm.
 * User: Dmitry Andreevich
 * Date: 25.09.2018
 * Time: 19:17
 */

namespace app\controllers;


use Aws\S3\S3Client;
use Codeception\Module\Yii2;
use Faker\Provider\File;
use League\Flysystem\Adapter\Local;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;
use Yii;
use yii\base\Exception;
use yii\base\Module;
use yii\helpers\FileHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\UploadedFile;

class MainController extends Controller
{
    protected $fsAdapter = null;
    protected $fileSystemRootPath = 'filesystem';
    protected $configAwsS3 = [
        'key' => '',
        'secret' => '',
        'bucket' => '',
        'region' => 'us-east-2',
        'version' => 'latest'
    ];
    protected $keyS3 = '';
    protected $secretS3 = '';
    protected $bucketNameS3 = '';

    public function __construct($id, Module $module, array $config = [])
    {
        $this->enableCsrfValidation = false;

        $this->switchAdapter();

        parent::__construct($id, $module, $config);
    }

    public function beforeAction($action)
    {
        if($this->fsAdapter == null) {
            $this->fsAdapter = new Local(__DIR__ . '/../' . $this->fileSystemRootPath);
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }


    public function actionGetFilesData()
    {
        if($this->fsAdapter) {
            $path = Yii::$app->request->post('path');
            $fs = new Filesystem($this->fsAdapter);
            $content = $fs->listContents("/$path");

            echo json_encode($content, JSON_FORCE_OBJECT);
            exit;
        }

        echo '{ "type": "error" }';
        exit;
    }
    public function actionDelete()
    {
        if($this->fsAdapter){
            $type = Yii::$app->request->post('type'); // dir or another file
            $path = Yii::$app->request->post('path');

            if( isset($path) && !empty($path) ) {
                if( isset($type) && !empty($type) ){
                    $fs = new Filesystem($this->fsAdapter);

                    if( $fs->has($path) ){
                        if($type === 'dir')
                            $fs->deleteDir($path);
                        else
                            $fs->delete($path);

                        exit;
                    }
                }
            }
        }

        echo '{ "type": "error" }';
        exit;
    }

    public function actionNewFolder()
    {
        if($this->fsAdapter){
            $folderName = Yii::$app->request->post('name');
            $path = Yii::$app->request->post('path');

            if( isset($folderName) && !empty($folderName) ) {
                $fs = new Filesystem($this->fsAdapter);

                if(!$fs->has("$path/$folderName"))
                    $fs->createDir("$path/$folderName");
            }
        }

        echo '{ "type": "error" }';
        exit;
    }

    public function actionRename()
    {
        if($this->fsAdapter){
            $path = Yii::$app->request->post('path');
            $newPath = Yii::$app->request->post('newPath');

            if( isset($path) && isset($newPath) ) {
                $fs = new Filesystem($this->fsAdapter);

                if( $fs->has($path) )
                    $fs->rename($path, $newPath);
            }
        }

        echo '{ "type": "error" }';
        exit;
    }

    public function actionGetContent()
    {
        if($this->fsAdapter){
            $path = Yii::$app->request->post('path');

            if( isset($path) ) {
                $fs = new Filesystem($this->fsAdapter);

                if( $fs->has($path) ){
                    $file = $fs->get($path);

                    if($file->getType() !== 'dir') {
                        $content = $file->read();
                        $response = [
                            'type' => $file->getMimetype(),
                            'basename' => basename(__DIR__ . '/../' . $this->fileSystemRootPath . '/' . $path),
                            'content' => strstr($file->getMimetype(), 'image') ? base64_encode($content) : $content
                        ];

                        echo json_encode($response);
                        exit;
                    }
                }
            }
        }

        echo '{ "type": "error" }';
        exit;
    }

    public function actionCreateOrRewriteFile()
    {
        if($this->fsAdapter){
            $path = Yii::$app->request->post('path');
            $content = Yii::$app->request->post('content');

            if( isset($path) && isset($content) ) {
                $fs = new Filesystem($this->fsAdapter);

                if( $fs->has($path) ) {
                    $fs->update($path, $content);
                } else{
                    $fs->write($path, $content);
                }

                exit;
            }
        }

        echo '{ "type": "error" }';
        exit;
    }

    public function actionUpload()
    {
        $file = UploadedFile::getInstanceByName('file');
        $pathToSave = Yii::$app->request->post('path');
        if($file) {
            $fs = new Filesystem($this->fsAdapter);

            $fileSize = $file->size;
            $tmpPath = $file->tempName;

            /**
             * try file_get_contents($tmpPath);
             */
            $f = fopen($tmpPath, 'r');
            $content = fread($f, $fileSize);
            fclose($f);

            $pathToSave .= '/' . $file->getBaseName() . '.' . $file->getExtension();
            $fs->write($pathToSave, $content);

            echo $pathToSave;
            exit;
        }
    }

    protected function switchAdapter(){
        $selectedStore = Yii::$app->request->post('selectedStore');

        if ($selectedStore == 'S3'){
            $client = new S3Client([
                'credentials' => [
                    'key'    => $this->configAwsS3['key'],
                    'secret' => $this->configAwsS3['secret']
                ],
                'region' => $this->configAwsS3['region'],
                'version' => $this->configAwsS3['version'],
            ]);

            $this->fsAdapter = new AwsS3Adapter($client, $this->configAwsS3['bucket']);
        }else {
            $this->fsAdapter = new Local(__DIR__ . '/../' . $this->fileSystemRootPath);
        }
    }
}